# Generated by Django 5.2.4 on 2025-11-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_amount_payment_amount_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='variations',
            new_name='variation',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='color',
            field=models.CharField(default='replace', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='size',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
